homepage:
    pattern:  /
    defaults: { _controller: FrameworkBundle:Default:index }

hello:
    resource: HelloBundle/Resources/config/routing.yml

_internal:
    resource: FrameworkBundle/Resources/config/routing/internal.xml
    prefix:   /_internal
